#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 acceleration_confidence
int64 ACCELERATION_CONFIDENCE_RANGE_MIN = 0
int64 ACCELERATION_CONFIDENCE_RANGE_MAX = 102
int64 ACCELERATION_CONFIDENCE_POINT_ONE_METER_PER_SEC_SQUARED = 1
int64 ACCELERATION_CONFIDENCE_OUT_OF_RANGE = 101
int64 ACCELERATION_CONFIDENCE_UNAVAILABLE = 102
