#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 altitude_value
int64 ALTITUDE_VALUE_RANGE_MIN = -100000
int64 ALTITUDE_VALUE_RANGE_MAX = 800001
int64 ALTITUDE_VALUE_REFERENCE_ELLIPSOID_SURFACE = 0
int64 ALTITUDE_VALUE_ONE_CENTIMETER = 1
int64 ALTITUDE_VALUE_UNAVAILABLE = 800001
