#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



Latitude protected_zone_latitude

Longitude protected_zone_longitude

# Optional Field
bool cen_dsrc_tolling_zone_id_present 0
CenDsrcTollingZoneID cen_dsrc_tolling_zone_id
