#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool innerhard_shoulder_status_present 0
HardShoulderStatus innerhard_shoulder_status

# Optional Field
bool outerhard_shoulder_status_present 0
HardShoulderStatus outerhard_shoulder_status

# Optional Field
bool driving_lane_status_present 0
DrivingLaneStatus driving_lane_status
