#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool innerhard_shoulder_status_present 0
HardShoulderStatus innerhard_shoulder_status

# Optional Field
bool outerhard_shoulder_status_present 0
HardShoulderStatus outerhard_shoulder_status

# Optional Field
bool driving_lane_status_present 0
DrivingLaneStatus driving_lane_status
