#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 curvature_calculation_mode
int64 CURVATURE_CALCULATION_MODE_YAW_RATE_USED = 0
int64 CURVATURE_CALCULATION_MODE_YAW_RATE_NOT_USED = 1
int64 CURVATURE_CALCULATION_MODE_UNAVAILABLE = 2
