#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 curvature_confidence
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_00002 = 0
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_0001 = 1
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_0005 = 2
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_002 = 3
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_01 = 4
int64 CURVATURE_CONFIDENCE_ONE_PER_METER_0_1 = 5
int64 CURVATURE_CONFIDENCE_OUT_OF_RANGE = 6
int64 CURVATURE_CONFIDENCE_UNAVAILABLE = 7
