#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 delta_altitude
int64 DELTA_ALTITUDE_RANGE_MIN = -12700
int64 DELTA_ALTITUDE_RANGE_MAX = 12800
int64 DELTA_ALTITUDE_ONE_CENTIMETER_UP = 1
int64 DELTA_ALTITUDE_ONE_CENTIMETER_DOWN = -1
int64 DELTA_ALTITUDE_UNAVAILABLE = 12800
