#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 delta_longitude
int64 DELTA_LONGITUDE_RANGE_MIN = -131071
int64 DELTA_LONGITUDE_RANGE_MAX = 131072
int64 DELTA_LONGITUDE_ONE_MICRODEGREE_EAST = 10
int64 DELTA_LONGITUDE_ONE_MICRODEGREE_WEST = -10
int64 DELTA_LONGITUDE_UNAVAILABLE = 131072
