#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 delta_latitude
int64 DELTA_LATITUDE_RANGE_MIN = -131071
int64 DELTA_LATITUDE_RANGE_MAX = 131072
int64 DELTA_LATITUDE_ONE_MICRODEGREE_NORTH = 10
int64 DELTA_LATITUDE_ONE_MICRODEGREE_SOUTH = -10
int64 DELTA_LATITUDE_UNAVAILABLE = 131072
