#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 delta_longitude
int64 DELTA_LONGITUDE_RANGE_MIN = -131071
int64 DELTA_LONGITUDE_RANGE_MAX = 131072
int64 DELTA_LONGITUDE_ONE_MICRODEGREE_EAST = 10
int64 DELTA_LONGITUDE_ONE_MICRODEGREE_WEST = -10
int64 DELTA_LONGITUDE_UNAVAILABLE = 131072
