#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 energy_storage_type
int64 ENERGY_STORAGE_TYPE_HYDROGEN_STORAGE = 0
int64 ENERGY_STORAGE_TYPE_ELECTRIC_ENERGY_STORAGE = 1
int64 ENERGY_STORAGE_TYPE_LIQUID_PROPANE_GAS = 2
int64 ENERGY_STORAGE_TYPE_COMPRESSED_NATURAL_GAS = 3
int64 ENERGY_STORAGE_TYPE_DIESEL = 4
int64 ENERGY_STORAGE_TYPE_GASOLINE = 5
int64 ENERGY_STORAGE_TYPE_AMMONIA = 6
