#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 exterior_lights
int64 EXTERIOR_LIGHTS_LOW_BEAM_HEADLIGHTS_ON = 0
int64 EXTERIOR_LIGHTS_HIGH_BEAM_HEADLIGHTS_ON = 1
int64 EXTERIOR_LIGHTS_LEFT_TURN_SIGNAL_ON = 2
int64 EXTERIOR_LIGHTS_RIGHT_TURN_SIGNAL_ON = 3
int64 EXTERIOR_LIGHTS_DAYTIME_RUNNING_LIGHTS_ON = 4
int64 EXTERIOR_LIGHTS_REVERSE_LIGHT_ON = 5
int64 EXTERIOR_LIGHTS_FOG_LIGHT_ON = 6
int64 EXTERIOR_LIGHTS_PARKING_LIGHTS_ON = 7
