#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 hard_shoulder_status
int64 HARD_SHOULDER_STATUS_AVAILABLE_FOR_STOPPING = 0
int64 HARD_SHOULDER_STATUS_CLOSED = 1
int64 HARD_SHOULDER_STATUS_AVAILABLE_FOR_DRIVING = 2
