#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 heading_value
int64 HEADING_VALUE_RANGE_MIN = 0
int64 HEADING_VALUE_RANGE_MAX = 3601
int64 HEADING_VALUE_WGS84NORTH = 0
int64 HEADING_VALUE_WGS84EAST = 900
int64 HEADING_VALUE_WGS84SOUTH = 1800
int64 HEADING_VALUE_WGS84WEST = 2700
int64 HEADING_VALUE_UNAVAILABLE = 3601
