#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 height_lon_carr
int64 HEIGHT_LON_CARR_RANGE_MIN = 1
int64 HEIGHT_LON_CARR_RANGE_MAX = 100
int64 HEIGHT_LON_CARR_ONE_CENTIMETER = 1
int64 HEIGHT_LON_CARR_UNAVAILABLE = 100
