#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 human_problem_sub_cause_code
int64 HUMAN_PROBLEM_SUB_CAUSE_CODE_RANGE_MIN = 0
int64 HUMAN_PROBLEM_SUB_CAUSE_CODE_RANGE_MAX = 255
int64 HUMAN_PROBLEM_SUB_CAUSE_CODE_UNAVAILABLE = 0
int64 HUMAN_PROBLEM_SUB_CAUSE_CODE_GLYCEMIA_PROBLEM = 1
int64 HUMAN_PROBLEM_SUB_CAUSE_CODE_HEART_PROBLEM = 2
