#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 human_presence_on_the_road_sub_cause_code
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_RANGE_MIN = 0
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_RANGE_MAX = 255
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_UNAVAILABLE = 0
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_CHILDREN_ON_ROADWAY = 1
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_CYCLIST_ON_ROADWAY = 2
int64 HUMAN_PRESENCE_ON_THE_ROAD_SUB_CAUSE_CODE_MOTORCYCLIST_ON_ROADWAY = 3
