#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 information_quality
int64 INFORMATION_QUALITY_RANGE_MIN = 0
int64 INFORMATION_QUALITY_RANGE_MAX = 7
int64 INFORMATION_QUALITY_UNAVAILABLE = 0
int64 INFORMATION_QUALITY_LOWEST = 1
int64 INFORMATION_QUALITY_HIGHEST = 7
