#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 information_quality
int64 INFORMATION_QUALITY_RANGE_MIN = 0
int64 INFORMATION_QUALITY_RANGE_MAX = 7
int64 INFORMATION_QUALITY_UNAVAILABLE = 0
int64 INFORMATION_QUALITY_LOWEST = 1
int64 INFORMATION_QUALITY_HIGHEST = 7
