#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 protocol_version
int64 PROTOCOL_VERSION_RANGE_MIN = 0
int64 PROTOCOL_VERSION_RANGE_MAX = 255

int64 message_id
int64 MESSAGE_ID_RANGE_MIN = 0
int64 MESSAGE_ID_RANGE_MAX = 255
int64 MESSAGE_ID_DENM = 1
int64 MESSAGE_ID_CAM = 2
int64 MESSAGE_ID_POI = 3
int64 MESSAGE_ID_SPATEM = 4
int64 MESSAGE_ID_MAPEM = 5
int64 MESSAGE_ID_IVIM = 6
int64 MESSAGE_ID_EV_RSR = 7
int64 MESSAGE_ID_TISTPGTRANSACTION = 8
int64 MESSAGE_ID_SREM = 9
int64 MESSAGE_ID_SSEM = 10
int64 MESSAGE_ID_EVCSN = 11
int64 MESSAGE_ID_SAEM = 12
int64 MESSAGE_ID_RTCMEM = 13

StationID station_id
