#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 lane_position
int64 LANE_POSITION_RANGE_MIN = -1
int64 LANE_POSITION_RANGE_MAX = 14
int64 LANE_POSITION_OFF_THE_ROAD = -1
int64 LANE_POSITION_INNER_HARD_SHOULDER = 0
int64 LANE_POSITION_INNERMOST_DRIVING_LANE = 1
int64 LANE_POSITION_SECOND_LANE_FROM_INSIDE = 2
int64 LANE_POSITION_OUTER_HARD_SHOULDER = 14
