#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 latitude
int64 LATITUDE_RANGE_MIN = -900000000
int64 LATITUDE_RANGE_MAX = 900000001
int64 LATITUDE_ONE_MICRODEGREE_NORTH = 10
int64 LATITUDE_ONE_MICRODEGREE_SOUTH = -10
int64 LATITUDE_UNAVAILABLE = 900000001
