#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 longitude
int64 LONGITUDE_RANGE_MIN = -1800000000
int64 LONGITUDE_RANGE_MAX = 1800000001
int64 LONGITUDE_ONE_MICRODEGREE_EAST = 10
int64 LONGITUDE_ONE_MICRODEGREE_WEST = -10
int64 LONGITUDE_UNAVAILABLE = 1800000001
