#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 longitudinal_acceleration_value
int64 LONGITUDINAL_ACCELERATION_VALUE_RANGE_MIN = -160
int64 LONGITUDINAL_ACCELERATION_VALUE_RANGE_MAX = 161
int64 LONGITUDINAL_ACCELERATION_VALUE_POINT_ONE_METER_PER_SEC_SQUARED_FORWARD = 1
int64 LONGITUDINAL_ACCELERATION_VALUE_POINT_ONE_METER_PER_SEC_SQUARED_BACKWARD = -1
int64 LONGITUDINAL_ACCELERATION_VALUE_UNAVAILABLE = 161
