#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 number_of_occupants
int64 NUMBER_OF_OCCUPANTS_RANGE_MIN = 0
int64 NUMBER_OF_OCCUPANTS_RANGE_MAX = 127
int64 NUMBER_OF_OCCUPANTS_ONE_OCCUPANT = 1
int64 NUMBER_OF_OCCUPANTS_UNAVAILABLE = 127
