#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 performance_class
int64 PERFORMANCE_CLASS_RANGE_MIN = 0
int64 PERFORMANCE_CLASS_RANGE_MAX = 7
int64 PERFORMANCE_CLASS_UNAVAILABLE = 0
int64 PERFORMANCE_CLASS_PERFORMANCE_CLASS_A = 1
int64 PERFORMANCE_CLASS_PERFORMANCE_CLASS_B = 2
