#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 pos_cent_mass
int64 POS_CENT_MASS_RANGE_MIN = 1
int64 POS_CENT_MASS_RANGE_MAX = 63
int64 POS_CENT_MASS_TEN_CENTIMETERS = 1
int64 POS_CENT_MASS_UNAVAILABLE = 63
