#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 positioning_solution_type
int64 POSITIONING_SOLUTION_TYPE_NO_POSITIONING_SOLUTION = 0
int64 POSITIONING_SOLUTION_TYPE_S_GNSS = 1
int64 POSITIONING_SOLUTION_TYPE_D_GNSS = 2
int64 POSITIONING_SOLUTION_TYPE_S_GNSSPLUS_DR = 3
int64 POSITIONING_SOLUTION_TYPE_D_GNSSPLUS_DR = 4
int64 POSITIONING_SOLUTION_TYPE_D_R = 5
