#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



ProtectedZoneType protected_zone_type

# Optional Field
bool expiry_time_present 0
TimestampIts expiry_time

Latitude protected_zone_latitude

Longitude protected_zone_longitude

# Optional Field
bool protected_zone_radius_present 0
ProtectedZoneRadius protected_zone_radius

# Optional Field
bool protected_zone_id_present 0
ProtectedZoneID protected_zone_id
