#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 pt_activation_type
int64 PT_ACTIVATION_TYPE_RANGE_MIN = 0
int64 PT_ACTIVATION_TYPE_RANGE_MAX = 255
int64 PT_ACTIVATION_TYPE_UNDEFINED_CODING_TYPE = 0
int64 PT_ACTIVATION_TYPE_R09_16CODING_TYPE = 1
int64 PT_ACTIVATION_TYPE_VDV_50149CODING_TYPE = 2
