#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 relevance_distance
int64 RELEVANCE_DISTANCE_LESS_THAN50M = 0
int64 RELEVANCE_DISTANCE_LESS_THAN100M = 1
int64 RELEVANCE_DISTANCE_LESS_THAN200M = 2
int64 RELEVANCE_DISTANCE_LESS_THAN500M = 3
int64 RELEVANCE_DISTANCE_LESS_THAN1000M = 4
int64 RELEVANCE_DISTANCE_LESS_THAN5KM = 5
int64 RELEVANCE_DISTANCE_LESS_THAN10KM = 6
int64 RELEVANCE_DISTANCE_OVER10KM = 7
