#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 relevance_traffic_direction
int64 RELEVANCE_TRAFFIC_DIRECTION_ALL_TRAFFIC_DIRECTIONS = 0
int64 RELEVANCE_TRAFFIC_DIRECTION_UPSTREAM_TRAFFIC = 1
int64 RELEVANCE_TRAFFIC_DIRECTION_DOWNSTREAM_TRAFFIC = 2
int64 RELEVANCE_TRAFFIC_DIRECTION_OPPOSITE_TRAFFIC = 3
