#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 semi_axis_length
int64 SEMI_AXIS_LENGTH_RANGE_MIN = 0
int64 SEMI_AXIS_LENGTH_RANGE_MAX = 4095
int64 SEMI_AXIS_LENGTH_ONE_CENTIMETER = 1
int64 SEMI_AXIS_LENGTH_OUT_OF_RANGE = 4094
int64 SEMI_AXIS_LENGTH_UNAVAILABLE = 4095
