#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 signal_violation_sub_cause_code
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_RANGE_MIN = 0
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_RANGE_MAX = 255
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_UNAVAILABLE = 0
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_STOP_SIGN_VIOLATION = 1
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_TRAFFIC_LIGHT_VIOLATION = 2
int64 SIGNAL_VIOLATION_SUB_CAUSE_CODE_TURNING_REGULATION_VIOLATION = 3
