#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 special_transport_type
int64 SPECIAL_TRANSPORT_TYPE_HEAVY_LOAD = 0
int64 SPECIAL_TRANSPORT_TYPE_EXCESS_WIDTH = 1
int64 SPECIAL_TRANSPORT_TYPE_EXCESS_LENGTH = 2
int64 SPECIAL_TRANSPORT_TYPE_EXCESS_HEIGHT = 3
