#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 speed_value
int64 SPEED_VALUE_RANGE_MIN = 0
int64 SPEED_VALUE_RANGE_MAX = 16383
int64 SPEED_VALUE_STANDSTILL = 0
int64 SPEED_VALUE_ONE_CENTIMETER_PER_SEC = 1
int64 SPEED_VALUE_UNAVAILABLE = 16383
