#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 stationary_since
int64 STATIONARY_SINCE_LESS_THAN1MINUTE = 0
int64 STATIONARY_SINCE_LESS_THAN2MINUTES = 1
int64 STATIONARY_SINCE_LESS_THAN15MINUTES = 2
int64 STATIONARY_SINCE_EQUAL_OR_GREATER15MINUTES = 3
