#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 steering_wheel_angle_confidence
int64 STEERING_WHEEL_ANGLE_CONFIDENCE_RANGE_MIN = 1
int64 STEERING_WHEEL_ANGLE_CONFIDENCE_RANGE_MAX = 127
int64 STEERING_WHEEL_ANGLE_CONFIDENCE_EQUAL_OR_WITHIN_ONE_POINT_FIVE_DEGREE = 1
int64 STEERING_WHEEL_ANGLE_CONFIDENCE_OUT_OF_RANGE = 126
int64 STEERING_WHEEL_ANGLE_CONFIDENCE_UNAVAILABLE = 127
