#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 steering_wheel_angle_value
int64 STEERING_WHEEL_ANGLE_VALUE_RANGE_MIN = -511
int64 STEERING_WHEEL_ANGLE_VALUE_RANGE_MAX = 512
int64 STEERING_WHEEL_ANGLE_VALUE_STRAIGHT = 0
int64 STEERING_WHEEL_ANGLE_VALUE_ONE_POINT_FIVE_DEGREES_TO_RIGHT = -1
int64 STEERING_WHEEL_ANGLE_VALUE_ONE_POINT_FIVE_DEGREES_TO_LEFT = 1
int64 STEERING_WHEEL_ANGLE_VALUE_UNAVAILABLE = 512
