#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 temperature
int64 TEMPERATURE_RANGE_MIN = -60
int64 TEMPERATURE_RANGE_MAX = 67
int64 TEMPERATURE_EQUAL_OR_SMALLER_THAN_MINUS60DEG = -60
int64 TEMPERATURE_ONE_DEGREE_CELSIUS = 1
int64 TEMPERATURE_EQUAL_OR_GREATER_THAN67DEG = 67
