#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 transmission_interval
int64 TRANSMISSION_INTERVAL_RANGE_MIN = 1
int64 TRANSMISSION_INTERVAL_RANGE_MAX = 10000
int64 TRANSMISSION_INTERVAL_ONE_MILLI_SECOND = 1
int64 TRANSMISSION_INTERVAL_TEN_SECONDS = 10000
