#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 turning_radius
int64 TURNING_RADIUS_RANGE_MIN = 1
int64 TURNING_RADIUS_RANGE_MAX = 255
int64 TURNING_RADIUS_POINT4METERS = 1
int64 TURNING_RADIUS_UNAVAILABLE = 255
