#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 validity_duration
int64 VALIDITY_DURATION_RANGE_MIN = 0
int64 VALIDITY_DURATION_RANGE_MAX = 86400
int64 VALIDITY_DURATION_TIME_OF_DETECTION = 0
int64 VALIDITY_DURATION_ONE_SECOND_AFTER_DETECTION = 1
