#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 vehicle_length_value
int64 VEHICLE_LENGTH_VALUE_RANGE_MIN = 1
int64 VEHICLE_LENGTH_VALUE_RANGE_MAX = 1023
int64 VEHICLE_LENGTH_VALUE_TEN_CENTIMETERS = 1
int64 VEHICLE_LENGTH_VALUE_OUT_OF_RANGE = 1022
int64 VEHICLE_LENGTH_VALUE_UNAVAILABLE = 1023
