#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 vehicle_width
int64 VEHICLE_WIDTH_RANGE_MIN = 1
int64 VEHICLE_WIDTH_RANGE_MAX = 62
int64 VEHICLE_WIDTH_TEN_CENTIMETERS = 1
int64 VEHICLE_WIDTH_OUT_OF_RANGE = 61
int64 VEHICLE_WIDTH_UNAVAILABLE = 62
