#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 vertical_acceleration_value
int64 VERTICAL_ACCELERATION_VALUE_RANGE_MIN = -160
int64 VERTICAL_ACCELERATION_VALUE_RANGE_MAX = 161
int64 VERTICAL_ACCELERATION_VALUE_POINT_ONE_METER_PER_SEC_SQUARED_UP = 1
int64 VERTICAL_ACCELERATION_VALUE_POINT_ONE_METER_PER_SEC_SQUARED_DOWN = -1
int64 VERTICAL_ACCELERATION_VALUE_UNAVAILABLE = 161
