#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 wrong_way_driving_sub_cause_code
int64 WRONG_WAY_DRIVING_SUB_CAUSE_CODE_RANGE_MIN = 0
int64 WRONG_WAY_DRIVING_SUB_CAUSE_CODE_RANGE_MAX = 255
int64 WRONG_WAY_DRIVING_SUB_CAUSE_CODE_UNAVAILABLE = 0
int64 WRONG_WAY_DRIVING_SUB_CAUSE_CODE_WRONG_LANE = 1
int64 WRONG_WAY_DRIVING_SUB_CAUSE_CODE_WRONG_DIRECTION = 2
