#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 yaw_rate_value
int64 YAW_RATE_VALUE_RANGE_MIN = -32766
int64 YAW_RATE_VALUE_RANGE_MAX = 32767
int64 YAW_RATE_VALUE_STRAIGHT = 0
int64 YAW_RATE_VALUE_DEG_SEC_000_01TO_RIGHT = -1
int64 YAW_RATE_VALUE_DEG_SEC_000_01TO_LEFT = 1
int64 YAW_RATE_VALUE_UNAVAILABLE = 32767
