#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 yaw_rate_confidence
int64 YAW_RATE_CONFIDENCE_DEG_SEC_000_01 = 0
int64 YAW_RATE_CONFIDENCE_DEG_SEC_000_05 = 1
int64 YAW_RATE_CONFIDENCE_DEG_SEC_000_10 = 2
int64 YAW_RATE_CONFIDENCE_DEG_SEC_001_00 = 3
int64 YAW_RATE_CONFIDENCE_DEG_SEC_005_00 = 4
int64 YAW_RATE_CONFIDENCE_DEG_SEC_010_00 = 5
int64 YAW_RATE_CONFIDENCE_DEG_SEC_100_00 = 6
int64 YAW_RATE_CONFIDENCE_OUT_OF_RANGE = 7
int64 YAW_RATE_CONFIDENCE_UNAVAILABLE = 8
