#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



int64 manufacturerid
int64 MANUFACTURERID_RANGE_MIN = 0
int64 MANUFACTURERID_RANGE_MAX = 65535

int64 individualid
int64 INDIVIDUALID_RANGE_MIN = 0
int64 INDIVIDUALID_RANGE_MAX = 134217727
