#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



BeaconID rsu

Time time

Profile profile

ApplicationList mand_applications

# Optional Field
bool nonmand_applications_present 0
ApplicationList nonmand_applications


Profile[] list #size(0..127)
