#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 equipment_class
int64 EQUIPMENT_CLASS_RANGE_MIN = 0
int64 EQUIPMENT_CLASS_RANGE_MAX = 32767

int64 manufacturer_id
int64 MANUFACTURER_ID_RANGE_MIN = 0
int64 MANUFACTURER_ID_RANGE_MAX = 65535

# Optional Field
bool obe_status_present 0
int64 obe_status
int64 OBE_STATUS_RANGE_MIN = 0
int64 OBE_STATUS_RANGE_MAX = 65535
