#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 fill

bool mode

DsrcEID eid

# Optional Field
bool access_credentials_present 0
int64[] access_credentials #size(0..127)


AttributeList attr_list

# Optional Field
bool iid_present 0
DsrcEID iid
