#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


# CHOICE! - Choose exactly of the containers
int64 ext2_container_select 0
int64 EXT2_NOTHING = 0
int64 EXT2_CONTENT = 1
int64 EXT2_EXTENSION = 2

# container 1
int64 content

# container 2
Ext3 extension

