#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 var_length_number_container_select 0
int64 VAR_LENGTH_NUMBER_NOTHING = 0
int64 VAR_LENGTH_NUMBER_CONTENT = 1
int64 VAR_LENGTH_NUMBER_EXTENSION = 2

# container 1
int64 content

# container 2
Ext1 extension

