#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 var_length_number2_container_select 0
int64 VAR_LENGTH_NUMBER2_NOTHING = 0
int64 VAR_LENGTH_NUMBER2_SHORT_NO = 1
int64 VAR_LENGTH_NUMBER2_LONG_NO = 2

# container 1
int64 short_no

# container 2
int64 long_no

