#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Patrizia Neubauer (https://github.com/patrizianeubauer)
#

int64 fill

DsrcEID eid

# Optional Field
bool iid_present 0
DsrcEID iid

# container-reference not parsed
# Optional Field
bool response_parameter_present 0
int64 response_parameter

# Optional Field
bool ret_present 0
ReturnStatus ret
