#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Thu Jan 19 09:10:59 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
#

# Removed duplicates (UNIT_RANGE_MAX/MIN)

int64 value
int64 VALUE_RANGE_MIN = 1
int64 VALUE_RANGE_MAX = 16384

CodeUnits unit
int64 UNIT_RANGE_MIN = 2
int64 UNIT_RANGE_MAX = 4
