#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Thu Jan 19 09:10:59 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
#

# Parser cannot parse SEQUENCE OF Sequence at the moment

DSRCApplicationEntityID aid

# Optional Field
bool eid_present 0
DsrcEID eid

# Optional Field
bool parameter_present 0
ApplicationContextMark parameter