#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Patrizia Neubauer (https://github.com/patrizianeubauer)
#

# InternationalSignapplicablePeriod -> InternationalSignApplicablePeriod

LanePosition lane_number

Direction direction

# Optional Field
bool validity_present 0
InternationalSignApplicablePeriod validity

LaneType lane_type

# Optional Field
bool lane_type_qualifier_present 0
CompleteVehicleCharacteristics lane_type_qualifier

LaneStatus lane_status

# Optional Field
bool lane_width_present 0
IviLaneWidth lane_width

# Optional Field
bool detection_zone_ids_present 0
ZoneIds detection_zone_ids

# Optional Field
bool relevance_zone_ids_present 0
ZoneIds relevance_zone_ids

# Optional Field
bool lane_characteristics_present 0
LaneCharacteristics lane_characteristics

# Optional Field
bool lane_surface_static_characteristics_present 0
RoadSurfaceStaticCharacteristics lane_surface_static_characteristics

# Optional Field
bool lane_surface_dynamic_characteristics_present 0
RoadSurfaceDynamicCharacteristics lane_surface_dynamic_characteristics
