#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Thu Jan 19 09:10:59 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
#

# Adaptation of the integer enumeration

int64 return_status
int64 RETURN_STATUS_NO_ERROR = 0
int64 RETURN_STATUS_ACCESS_DENIED = 1
int64 RETURN_STATUS_ARGUMENT_ERROR = 2
int64 RETURN_STATUS_COMPLEXITY_LIMITATION = 3
int64 RETURN_STATUS_PROCESSING_FAILURE = 4
int64 RETURN_STATUS_PROCESSING = 5
int64 RETURN_STATUS_CHAINING_ERROR = 6

