#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



AreaType type

int64 distance_a
int64 DISTANCE_A_RANGE_MIN = 0
int64 DISTANCE_A_RANGE_MAX = 65535

int64 distance_b
int64 DISTANCE_B_RANGE_MIN = 0
int64 DISTANCE_B_RANGE_MAX = 65535

int64 angle
int64 ANGLE_RANGE_MIN = 0
int64 ANGLE_RANGE_MAX = 65535
