#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



int64 latitude
int64 LATITUDE_RANGE_MIN = -2147483648
int64 LATITUDE_RANGE_MAX = 2147483647

int64 longitude
int64 LONGITUDE_RANGE_MIN = -2147483648
int64 LONGITUDE_RANGE_MAX = 2147483647
