#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool lane_position_present 0
LanePosition lane_position

# Optional Field
bool impact_reduction_present 0
ImpactReductionContainer impact_reduction

# Optional Field
bool external_temperature_present 0
Temperature external_temperature

# Optional Field
bool road_works_present 0
RoadWorksContainerExtended road_works

# Optional Field
bool positioning_solution_present 0
PositioningSolutionType positioning_solution

# Optional Field
bool stationary_vehicle_present 0
StationaryVehicleContainer stationary_vehicle
