#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



ManagementContainer management

# Optional Field
bool situation_present 0
SituationContainer situation

# Optional Field
bool location_present 0
LocationContainer location

# Optional Field
bool alacarte_present 0
AlacarteContainer alacarte
