#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



ManagementContainer management

# Optional Field
bool situation_present 0
SituationContainer situation

# Optional Field
bool location_present 0
LocationContainer location

# Optional Field
bool alacarte_present 0
AlacarteContainer alacarte
