#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



HeightLonCarr height_lon_carr_left

HeightLonCarr height_lon_carr_right

PosLonCarr pos_lon_carr_left

PosLonCarr pos_lon_carr_right

PositionOfPillars position_of_pillars

PosCentMass pos_cent_mass

WheelBaseVehicle wheel_base_vehicle

TurningRadius turning_radius

PosFrontAx pos_front_ax

PositionOfOccupants position_of_occupants

VehicleMass vehicle_mass

RequestResponseIndication request_response_indication
