#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool event_speed_present 0
Speed event_speed

# Optional Field
bool event_position_heading_present 0
Heading event_position_heading

Traces traces

# Optional Field
bool road_type_present 0
RoadType road_type
