#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool event_speed_present 0
Speed event_speed

# Optional Field
bool event_position_heading_present 0
Heading event_position_heading

Traces traces

# Optional Field
bool road_type_present 0
RoadType road_type
