#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



ActionID action_id

TimestampIts detection_time

TimestampIts reference_time

# Optional Field
bool termination_present 0
Termination termination

ReferencePosition event_position

# Optional Field
bool relevance_distance_present 0
RelevanceDistance relevance_distance

# Optional Field
bool relevance_traffic_direction_present 0
RelevanceTrafficDirection relevance_traffic_direction

# Optional Field
bool validity_duration_present 0
ValidityDuration validity_duration

# Optional Field
bool transmission_interval_present 0
TransmissionInterval transmission_interval

StationType station_type
