#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool light_bar_siren_in_use_present 0
LightBarSirenInUse light_bar_siren_in_use

# Optional Field
bool closed_lanes_present 0
ClosedLanes closed_lanes

# Optional Field
bool restriction_present 0
RestrictedTypes restriction

# Optional Field
bool speed_limit_present 0
SpeedLimit speed_limit

# Optional Field
bool incident_indication_present 0
CauseCode incident_indication

# Optional Field
bool recommended_path_present 0
ItineraryPath recommended_path

# Optional Field
bool starting_point_speed_limit_present 0
DeltaReferencePosition starting_point_speed_limit

# Optional Field
bool traffic_flow_rule_present 0
TrafficRule traffic_flow_rule

# Optional Field
bool reference_denms_present 0
ReferenceDenms reference_denms
