#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



InformationQuality information_quality

CauseCode event_type

# Optional Field
bool linked_cause_present 0
CauseCode linked_cause

# Optional Field
bool event_history_present 0
EventHistory event_history
