#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



InformationQuality information_quality

CauseCode event_type

# Optional Field
bool linked_cause_present 0
CauseCode linked_cause

# Optional Field
bool event_history_present 0
EventHistory event_history
