#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool stationary_since_present 0
StationarySince stationary_since

# Optional Field
bool stationary_cause_present 0
CauseCode stationary_cause

# Optional Field
bool carrying_dangerous_goods_present 0
DangerousGoodsExtended carrying_dangerous_goods

# Optional Field
bool number_of_occupants_present 0
NumberOfOccupants number_of_occupants

# Optional Field
bool vehicle_identification_present 0
VehicleIdentification vehicle_identification

# Optional Field
bool energy_storage_type_present 0
EnergyStorageType energy_storage_type
