#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 owner_code

int64 serial_number
int64 SERIAL_NUMBER_RANGE_MIN = 0
int64 SERIAL_NUMBER_RANGE_MAX = 1000000

int64 check_digit
int64 CHECK_DIGIT_RANGE_MIN = 0
int64 CHECK_DIGIT_RANGE_MAX = 10

int64 length
int64 LENGTH_RANGE_MIN = 1
int64 LENGTH_RANGE_MAX = 2000

int64 height
int64 HEIGHT_RANGE_MIN = 1
int64 HEIGHT_RANGE_MAX = 500

int64 width
int64 WIDTH_RANGE_MIN = 200
int64 WIDTH_RANGE_MAX = 300

int64 container_type_code
int64 CONTAINER_TYPE_CODE_RANGE_MIN = 0
int64 CONTAINER_TYPE_CODE_RANGE_MAX = 127

int64 maximum_gross_mass
int64 MAXIMUM_GROSS_MASS_RANGE_MIN = 19
int64 MAXIMUM_GROSS_MASS_RANGE_MAX = 500

int64 tare_mass
int64 TARE_MASS_RANGE_MIN = 0
int64 TARE_MASS_RANGE_MAX = 99

int64 fill
