#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 cop_value
int64 COP_VALUE_NO_ENTRY = 0
int64 COP_VALUE_CO2CLASS1 = 1
int64 COP_VALUE_CO2CLASS2 = 2
int64 COP_VALUE_CO2CLASS3 = 3
int64 COP_VALUE_CO2CLASS4 = 4
int64 COP_VALUE_CO2CLASS5 = 5
int64 COP_VALUE_CO2CLASS6 = 6
int64 COP_VALUE_CO2CLASS7 = 7
int64 COP_VALUE_RESERVEDFOR_USE = 8
