#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



int64 year
int64 YEAR_RANGE_MIN = 1990
int64 YEAR_RANGE_MAX = 2117

int64 month
int64 MONTH_RANGE_MIN = 0
int64 MONTH_RANGE_MAX = 12

int64 day
int64 DAY_RANGE_MIN = 0
int64 DAY_RANGE_MAX = 31
