#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



Provider contract_provider

int64[] type_of_contract #size(1..2)


int64 context_version
int64 CONTEXT_VERSION_RANGE_MIN = 0
int64 CONTEXT_VERSION_RANGE_MAX = 127
