#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 euro_value
int64 EURO_VALUE_NO_ENTRY = 0
int64 EURO_VALUE_EURO_1 = 1
int64 EURO_VALUE_EURO_2 = 2
int64 EURO_VALUE_EURO_3 = 3
int64 EURO_VALUE_EURO_4 = 4
int64 EURO_VALUE_EURO_5 = 5
int64 EURO_VALUE_EURO_6 = 6
int64 EURO_VALUE_RESERVED_FOR_USE1 = 7
int64 EURO_VALUE_RESERVED_FOR_USE2 = 8
int64 EURO_VALUE_RESERVED_FOR_USE3 = 9
int64 EURO_VALUE_RESERVED_FOR_USE4 = 10
int64 EURO_VALUE_RESERVED_FOR_USE5 = 11
int64 EURO_VALUE_RESERVED_FOR_USE6 = 12
int64 EURO_VALUE_RESERVED_FOR_USE7 = 13
int64 EURO_VALUE_RESERVED_FOR_USE8 = 14
int64 EURO_VALUE_EEV = 15
