#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



UnitType unit_type

int64 emission_co
int64 EMISSION_CO_RANGE_MIN = 0
int64 EMISSION_CO_RANGE_MAX = 32767

Int2 emission_hc

Int2 emission_nox

Int2 emission_hcnox
