#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 future_characteristics
int64 FUTURE_CHARACTERISTICS_RANGE_MIN = 0
int64 FUTURE_CHARACTERISTICS_RANGE_MAX = 255
int64 FUTURE_CHARACTERISTICS_NO_ENTRY = 0
int64 FUTURE_CHARACTERISTICS_AIR_SUSPENSION = 1
