#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 pos_of_first_instance
int64 POS_OF_FIRST_INSTANCE_RANGE_MIN = 0
int64 POS_OF_FIRST_INSTANCE_RANGE_MAX = 255

int64 pos_of_last_instance
int64 POS_OF_LAST_INSTANCE_RANGE_MIN = 0
int64 POS_OF_LAST_INSTANCE_RANGE_MAX = 255

AttributeIdList attribute_id_list
