#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



DateAndTime session_time

Provider session_service_provider

int64 station_location
int64 STATION_LOCATION_RANGE_MIN = 0
int64 STATION_LOCATION_RANGE_MAX = 1048575

int64 session_location

StationType type_of_session

ResultOp session_result_operational

ResultFin session_result_financial
