#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 set_mmirq
int64 SET_MMIRQ_RANGE_MIN = 0
int64 SET_MMIRQ_RANGE_MAX = 255
int64 SET_MMIRQ_OK = 0
int64 SET_MMIRQ_NOK = 1
int64 SET_MMIRQ_CONTACT_OPERATOR = 2
int64 SET_MMIRQ_NO_SIGNALLING = 255
