#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 signed_value_container_select 0
int64 SIGNED_VALUE_NOTHING = 0
int64 SIGNED_VALUE_POSITIVE = 1
int64 SIGNED_VALUE_NEGATIVE = 2

# container 1
int64 positive

# container 2
int64 negative

