#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 trailer_type
int64 TRAILER_TYPE_RANGE_MIN = 0
int64 TRAILER_TYPE_RANGE_MAX = 31
int64 TRAILER_TYPE_NOT_PRESENT = 0
int64 TRAILER_TYPE_TRAILER = 1
int64 TRAILER_TYPE_SEMITRAILER = 2

TrailerAxles trailer_axles
