#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



EnvironmentalCharacteristics environmental_characteristics

EngineCharacteristics engine_characteristics

DescriptiveCharacteristics descriptive_characteristics

FutureCharacteristics future_characteristics
