#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Int1 vehicle_first_axle_height


int64 tyre_type
int64 TYRE_TYPE_NOT_SPECIFIED = 0
int64 TYRE_TYPE_SINGLE_TYRE = 1
int64 TYRE_TYPE_DUAL_TYRES = 2
int64 TYRE_TYPE_RESERVED_FOR_USE = 3
int64 TYRE_TYPE_NUMBER_OF_AXLES = 1
TrailerAxles trailer_axles
TractorAxles tractor_axles
