#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Heading heading

Speed speed

DriveDirection drive_direction

VehicleLength vehicle_length

VehicleWidth vehicle_width

LongitudinalAcceleration longitudinal_acceleration

Curvature curvature

CurvatureCalculationMode curvature_calculation_mode

YawRate yaw_rate

# Optional Field
bool acceleration_control_present 0
AccelerationControl acceleration_control

# Optional Field
bool lane_position_present 0
LanePosition lane_position

# Optional Field
bool steering_wheel_angle_present 0
SteeringWheelAngle steering_wheel_angle

# Optional Field
bool lateral_acceleration_present 0
LateralAcceleration lateral_acceleration

# Optional Field
bool vertical_acceleration_present 0
VerticalAcceleration vertical_acceleration

# Optional Field
bool performance_class_present 0
PerformanceClass performance_class

# Optional Field
bool cen_dsrc_tolling_zone_present 0
CenDsrcTollingZone cen_dsrc_tolling_zone
