#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



BasicContainer basic_container

HighFrequencyContainer high_frequency_container

# Optional Field
bool low_frequency_container_present 0
LowFrequencyContainer low_frequency_container

# Optional Field
bool special_vehicle_container_present 0
SpecialVehicleContainer special_vehicle_container
