#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



BasicContainer basic_container

HighFrequencyContainer high_frequency_container

# Optional Field
bool low_frequency_container_present 0
LowFrequencyContainer low_frequency_container

# Optional Field
bool special_vehicle_container_present 0
SpecialVehicleContainer special_vehicle_container
