#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



LightBarSirenInUse light_bar_siren_in_use

# Optional Field
bool incident_indication_present 0
CauseCode incident_indication

# Optional Field
bool emergency_priority_present 0
EmergencyPriority emergency_priority
