#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 high_frequency_container_container_select 0
int64 HIGH_FREQUENCY_CONTAINER_NOTHING = 0
int64 HIGH_FREQUENCY_CONTAINER_BASIC_VEHICLE_CONTAINER_HIGH_FREQUENCY = 1
int64 HIGH_FREQUENCY_CONTAINER_RSU_CONTAINER_HIGH_FREQUENCY = 2

# container 1
BasicVehicleContainerHighFrequency basic_vehicle_container_high_frequency

# container 2
RSUContainerHighFrequency rsu_container_high_frequency

