#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 low_frequency_container_container_select 0
int64 LOW_FREQUENCY_CONTAINER_NOTHING = 0
int64 LOW_FREQUENCY_CONTAINER_BASIC_VEHICLE_CONTAINER_LOW_FREQUENCY = 1

# container 1
BasicVehicleContainerLowFrequency basic_vehicle_container_low_frequency

