#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool roadworks_sub_cause_code_present 0
RoadworksSubCauseCode roadworks_sub_cause_code

LightBarSirenInUse light_bar_siren_in_use

# Optional Field
bool closed_lanes_present 0
ClosedLanes closed_lanes
