#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



LightBarSirenInUse light_bar_siren_in_use

# Optional Field
bool incident_indication_present 0
CauseCode incident_indication

# Optional Field
bool traffic_rule_present 0
TrafficRule traffic_rule

# Optional Field
bool speed_limit_present 0
SpeedLimit speed_limit
