#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



PriorityLevel priority

SaeAutomationLevels allowed_sae_automation_levels

# Optional Field
bool min_gap_between_vehicles_present 0
GapBetweenVehicles min_gap_between_vehicles

# Optional Field
bool rec_gap_between_vehicles_present 0
GapBetweenVehicles rec_gap_between_vehicles

# Optional Field
bool automated_vehicle_max_speed_limit_present 0
SpeedValue automated_vehicle_max_speed_limit

# Optional Field
bool automated_vehicle_min_speed_limit_present 0
SpeedValue automated_vehicle_min_speed_limit

# Optional Field
bool automated_vehicle_speed_recommendation_present 0
SpeedValue automated_vehicle_speed_recommendation

# Optional Field
bool road_sign_codes_present 0
RoadSignCodes road_sign_codes

# Optional Field
bool extra_text_present 0
ConstraintTextLines2 extra_text
