#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool detection_zone_ids_present 0
ZoneIds detection_zone_ids

ZoneIds relevance_zone_ids

# Optional Field
bool direction_present 0
Direction direction

# Optional Field
bool applicable_lanes_present 0
LanePositions applicable_lanes

# Optional Field
bool vehicle_characteristics_present 0
VehicleCharacteristicsList vehicle_characteristics

# Optional Field
bool automated_vehicle_rules_present 0
AutomatedVehicleRules automated_vehicle_rules

# Optional Field
bool platooning_rules_present 0
PlatooningRules platooning_rules
