#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool tractor_present 0
TractorCharacteristics tractor

# Optional Field
bool trailer_present 0
TrailerCharacteristicsList trailer

# Optional Field
bool train_present 0
TrainCharacteristics train
