#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool tractor_present 0
TractorCharacteristics tractor

# Optional Field
bool trailer_present 0
TrailerCharacteristicsList trailer

# Optional Field
bool train_present 0
TrainCharacteristics train
