#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 comparison_operator
int64 COMPARISON_OPERATOR_RANGE_MIN = 0
int64 COMPARISON_OPERATOR_RANGE_MAX = 3
int64 COMPARISON_OPERATOR_GREATER_THAN = 0
int64 COMPARISON_OPERATOR_GREATER_THAN_OR_EQUAL_TO = 1
int64 COMPARISON_OPERATOR_LESS_THAN = 2
int64 COMPARISON_OPERATOR_LESS_THAN_OR_EQUAL_TO = 3
