#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



Zid zone_id

LanePosition lane_number

IviLaneWidth lane_width

# Optional Field
bool offset_distance_present 0
int64 offset_distance
int64 OFFSET_DISTANCE_RANGE_MIN = -32768
int64 OFFSET_DISTANCE_RANGE_MAX = 32767

# Optional Field
bool offset_position_present 0
DeltaReferencePosition offset_position
