#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 condition
int64 CONDITION_RANGE_MIN = 0
int64 CONDITION_RANGE_MAX = 15
int64 CONDITION_DRY = 0
int64 CONDITION_MOIST = 1
int64 CONDITION_WET = 2
int64 CONDITION_STANDING_WATER = 3
int64 CONDITION_FROST = 4
int64 CONDITION_ICE = 5
int64 CONDITION_SNOW = 6
int64 CONDITION_SLUSH = 7
int64 CONDITION_UNVAILABLE = 8
