#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 definition_accuracy
int64 DEFINITION_ACCURACY_RANGE_MIN = 0
int64 DEFINITION_ACCURACY_RANGE_MAX = 7
int64 DEFINITION_ACCURACY_ONE_CM = 0
int64 DEFINITION_ACCURACY_TWO_CM = 1
int64 DEFINITION_ACCURACY_FIVE_CM = 2
int64 DEFINITION_ACCURACY_TEN_CM = 3
int64 DEFINITION_ACCURACY_TWENTY_CM = 4
int64 DEFINITION_ACCURACY_FIFTY_CM = 5
int64 DEFINITION_ACCURACY_ONE_METER = 6
int64 DEFINITION_ACCURACY_UNAVAILABLE = 7
