#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 direction
int64 DIRECTION_RANGE_MIN = 0
int64 DIRECTION_RANGE_MAX = 3
int64 DIRECTION_SAME_DIRECTION = 0
int64 DIRECTION_OPPOSITE_DIRECTION = 1
int64 DIRECTION_BOTH_DIRECTIONS = 2
int64 DIRECTION_VALUE_NOT_USED = 3
