#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 driver_characteristics
int64 DRIVER_CHARACTERISTICS_RANGE_MIN = 0
int64 DRIVER_CHARACTERISTICS_RANGE_MAX = 3
int64 DRIVER_CHARACTERISTICS_UNEXPERIENCED_DRIVERS = 0
int64 DRIVER_CHARACTERISTICS_EXPERIENCED_DRIVERS = 1
int64 DRIVER_CHARACTERISTICS_RFU1 = 2
int64 DRIVER_CHARACTERISTICS_RFU2 = 3
