#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



ReferencePosition reference_position

# Optional Field
bool reference_position_time_present 0
TimestampIts reference_position_time

# Optional Field
bool reference_position_heading_present 0
Heading reference_position_heading

# Optional Field
bool reference_position_speed_present 0
Speed reference_position_speed

GlcParts parts
