#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Provider service_provider_id

IviIdentificationNumber ivi_identification_number

# Optional Field
bool time_stamp_present 0
TimestampIts time_stamp

# Optional Field
bool valid_from_present 0
TimestampIts valid_from

# Optional Field
bool valid_to_present 0
TimestampIts valid_to

# Optional Field
bool connected_ivi_structures_present 0
IviIdentificationNumbers connected_ivi_structures

IviStatus ivi_status

# Optional Field
bool connected_denms_present 0
ConnectedDenms connected_denms
