#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 ivi_purpose
int64 IVI_PURPOSE_RANGE_MIN = 0
int64 IVI_PURPOSE_RANGE_MAX = 3
int64 IVI_PURPOSE_SAFETY = 0
int64 IVI_PURPOSE_ENVIRONMENTAL = 1
int64 IVI_PURPOSE_TRAFFIC_OPTIMISATION = 2
