#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 ivi_status
int64 IVI_STATUS_RANGE_MIN = 0
int64 IVI_STATUS_RANGE_MAX = 7
int64 IVI_STATUS_NEW = 0
int64 IVI_STATUS_UPDATE = 1
int64 IVI_STATUS_CANCELLATION = 2
int64 IVI_STATUS_NEGATION = 3
