#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 ivi_type
int64 IVI_TYPE_RANGE_MIN = 0
int64 IVI_TYPE_RANGE_MAX = 7
int64 IVI_TYPE_IMMEDIATE_DANGER_WARNING_MESSAGES = 0
int64 IVI_TYPE_REGULATORY_MESSAGES = 1
int64 IVI_TYPE_TRAFFIC_RELATED_INFORMATION_MESSAGES = 2
int64 IVI_TYPE_POLLUTION_MESSAGES = 3
int64 IVI_TYPE_NOT_TRAFFIC_RELATED_INFORMATION_MESSAGES = 4
