#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 lane_delimitation
int64 LANE_DELIMITATION_RANGE_MIN = 0
int64 LANE_DELIMITATION_RANGE_MAX = 7
int64 LANE_DELIMITATION_NO_DELIMITATION = 0
int64 LANE_DELIMITATION_LOW_LANE_SEPARATOR = 1
int64 LANE_DELIMITATION_HIGH_LANE_SEPARATOR = 2
int64 LANE_DELIMITATION_WALL = 3
int64 LANE_DELIMITATION_CURB = 4
int64 LANE_DELIMITATION_UNPAVED = 5
int64 LANE_DELIMITATION_GUARDRAIL = 6
