#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



DefinitionAccuracy zone_definition_accuracy

LaneMarkingStatus existinglane_marking_status

MarkingColour newlane_marking_colour

LaneDelimitation lane_delimitation_left

LaneDelimitation lane_delimitation_right

Zid merging_with
