#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 lane_status
int64 LANE_STATUS_RANGE_MIN = 0
int64 LANE_STATUS_RANGE_MAX = 7
int64 LANE_STATUS_OPEN = 0
int64 LANE_STATUS_CLOSED = 1
int64 LANE_STATUS_MERGE_R = 2
int64 LANE_STATUS_MERGE_L = 3
int64 LANE_STATUS_MERGE_LR = 4
int64 LANE_STATUS_PROVISIONALLY_OPEN = 5
int64 LANE_STATUS_DIVERGING = 6
