#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 layout_component_id
int64 LAYOUT_COMPONENT_ID_RANGE_MIN = 1
int64 LAYOUT_COMPONENT_ID_RANGE_MAX = 8

int64 height
int64 HEIGHT_RANGE_MIN = 10
int64 HEIGHT_RANGE_MAX = 73

int64 width
int64 WIDTH_RANGE_MIN = 10
int64 WIDTH_RANGE_MAX = 265

int64 x
int64 X_RANGE_MIN = 10
int64 X_RANGE_MAX = 265

int64 y
int64 Y_RANGE_MIN = 10
int64 Y_RANGE_MAX = 73

int64 text_scripting
int64 TEXT_SCRIPTING_RANGE_MIN = 0
int64 TEXT_SCRIPTING_RANGE_MAX = 1
int64 TEXT_SCRIPTING_HORIZONTAL = 0
int64 TEXT_SCRIPTING_VERTICAL = 1
