#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 layout_id
int64 LAYOUT_ID_RANGE_MIN = 1
int64 LAYOUT_ID_RANGE_MAX = 4

# Optional Field
bool height_present 0
int64 height
int64 HEIGHT_RANGE_MIN = 10
int64 HEIGHT_RANGE_MAX = 73

# Optional Field
bool width_present 0
int64 width
int64 WIDTH_RANGE_MIN = 10
int64 WIDTH_RANGE_MAX = 265

LayoutComponents layout_components
