#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 marking_colour
int64 MARKING_COLOUR_RANGE_MIN = 0
int64 MARKING_COLOUR_RANGE_MAX = 7
int64 MARKING_COLOUR_WHITE = 0
int64 MARKING_COLOUR_YELLOW = 1
int64 MARKING_COLOUR_ORANGE = 2
int64 MARKING_COLOUR_RED = 3
int64 MARKING_COLOUR_BLUE = 4
int64 MARKING_COLOUR_UNAVAILABLE = 7
