#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 material_type
int64 MATERIAL_TYPE_RANGE_MIN = 0
int64 MATERIAL_TYPE_RANGE_MAX = 7
int64 MATERIAL_TYPE_ASPHALT = 0
int64 MATERIAL_TYPE_CONCRETE = 1
int64 MATERIAL_TYPE_COBBLESTONE = 2
int64 MATERIAL_TYPE_GRAVEL = 3
int64 MATERIAL_TYPE_UNAVAILABLE = 7
