#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



PriorityLevel priority

SaeAutomationLevels allowed_sae_automation_levels

# Optional Field
bool max_no_of_vehicles_present 0
MaxNoOfVehicles max_no_of_vehicles

# Optional Field
bool max_lenght_of_platoon_present 0
MaxLenghtOfPlatoon max_lenght_of_platoon

# Optional Field
bool min_gap_between_vehicles_present 0
GapBetweenVehicles min_gap_between_vehicles

# Optional Field
bool platoon_max_speed_limit_present 0
SpeedValue platoon_max_speed_limit

# Optional Field
bool platoon_min_speed_limit_present 0
SpeedValue platoon_min_speed_limit

# Optional Field
bool platoon_speed_recommendation_present 0
SpeedValue platoon_speed_recommendation

# Optional Field
bool road_sign_codes_present 0
RoadSignCodes road_sign_codes

# Optional Field
bool extra_text_present 0
ConstraintTextLines2 extra_text
