#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool detection_zone_ids_present 0
ZoneIds detection_zone_ids

ZoneIds relevance_zone_ids

# Optional Field
bool direction_present 0
Direction direction

# Optional Field
bool road_surface_static_characteristics_present 0
RoadSurfaceStaticCharacteristics road_surface_static_characteristics

# Optional Field
bool road_surface_dynamic_characteristics_present 0
RoadSurfaceDynamicCharacteristics road_surface_dynamic_characteristics
