#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 rscunit
int64 RSCUNIT_RANGE_MIN = 0
int64 RSCUNIT_RANGE_MAX = 15
int64 RSCUNIT_KMPERH = 0
int64 RSCUNIT_MILESPERH = 1
int64 RSCUNIT_KILOMETER = 2
int64 RSCUNIT_METER = 3
int64 RSCUNIT_DECIMETER = 4
int64 RSCUNIT_CENTIMETER = 5
int64 RSCUNIT_MILE = 6
int64 RSCUNIT_YARD = 7
int64 RSCUNIT_FOOT = 8
int64 RSCUNIT_MINUTES_OF_TIME = 9
int64 RSCUNIT_TONNES = 10
int64 RSCUNIT_HUNDREDKG = 11
int64 RSCUNIT_POUND = 12
int64 RSCUNIT_RATE_OF_INCLINE = 13
