#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool layout_component_id_present 0
int64 layout_component_id
int64 LAYOUT_COMPONENT_ID_RANGE_MIN = 1
int64 LAYOUT_COMPONENT_ID_RANGE_MAX = 4

int64 language

string text_content
