#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool equal_to_present 0
TrailerCharacteristicsFixValuesList equal_to

# Optional Field
bool not_equal_to_present 0
TrailerCharacteristicsFixValuesList not_equal_to

# Optional Field
bool ranges_present 0
TrailerCharacteristicsRangesList ranges
