#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 treatment_type
int64 TREATMENT_TYPE_RANGE_MIN = 0
int64 TREATMENT_TYPE_RANGE_MAX = 7
int64 TREATMENT_TYPE_NO = 0
int64 TREATMENT_TYPE_ANTISKID = 1
int64 TREATMENT_TYPE_ANTI_ICING = 2
int64 TREATMENT_TYPE_DE_ICING = 3
int64 TREATMENT_TYPE_UNAVAILABLE = 7
