#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 vc_class
int64 VC_CLASS_RANGE_MIN = 0
int64 VC_CLASS_RANGE_MAX = 7
int64 VC_CLASS_CLASS_A = 0
int64 VC_CLASS_CLASS_B = 1
int64 VC_CLASS_CLASS_C = 2
int64 VC_CLASS_CLASS_D = 3
int64 VC_CLASS_CLASS_E = 4
int64 VC_CLASS_CLASS_F = 5
int64 VC_CLASS_CLASS_G = 6
int64 VC_CLASS_CLASS_H = 7
