#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 vc_option
int64 VC_OPTION_RANGE_MIN = 0
int64 VC_OPTION_RANGE_MAX = 7
int64 VC_OPTION_NONE = 0
int64 VC_OPTION_A = 1
int64 VC_OPTION_B = 2
int64 VC_OPTION_C = 3
int64 VC_OPTION_D = 4
int64 VC_OPTION_E = 5
int64 VC_OPTION_F = 6
int64 VC_OPTION_G = 7
