#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 wear_level
int64 WEAR_LEVEL_RANGE_MIN = 0
int64 WEAR_LEVEL_RANGE_MAX = 7
int64 WEAR_LEVEL_NEW = 0
int64 WEAR_LEVEL_GOOD = 1
int64 WEAR_LEVEL_BAD = 2
int64 WEAR_LEVEL_HAS_POTHOLES = 3
int64 WEAR_LEVEL_UNAVAILABLE = 7
