#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



ConnectingLane connecting_lane

# Optional Field
bool remote_intersection_present 0
IntersectionReferenceID remote_intersection

# Optional Field
bool signal_group_present 0
SignalGroupID signal_group

# Optional Field
bool user_class_present 0
RestrictionClassID user_class

# Optional Field
bool connection_id_present 0
LaneConnectionID connection_id
