#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool process_method_present 0
string process_method

# Optional Field
bool process_agency_present 0
string process_agency

# Optional Field
bool last_checked_date_present 0
string last_checked_date

# Optional Field
bool geoid_used_present 0
string geoid_used
