#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool year_present 0
DYear year

# Optional Field
bool month_present 0
DMonth month

# Optional Field
bool day_present 0
DDay day

# Optional Field
bool hour_present 0
DHour hour

# Optional Field
bool minute_present 0
DMinute minute

# Optional Field
bool second_present 0
DSecond second

# Optional Field
bool offset_present 0
DOffset offset
