#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 dsrcmsg_id
int64 DSRCMSG_ID_RANGE_MIN = 0
int64 DSRCMSG_ID_RANGE_MAX = 32767
int64 DSRCMSG_ID_MAP_DATA = 18
int64 DSRCMSG_ID_RTCM_CORRECTIONS = 28
int64 DSRCMSG_ID_SIGNAL_PHASE_AND_TIMING_MESSAGE = 19
int64 DSRCMSG_ID_SIGNAL_REQUEST_MESSAGE = 29
int64 DSRCMSG_ID_SIGNAL_STATUS_MESSAGE = 30
