#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 emission_type
int64 EMISSION_TYPE_EURO1 = 0
int64 EMISSION_TYPE_EURO2 = 1
int64 EMISSION_TYPE_EURO3 = 2
int64 EMISSION_TYPE_EURO4 = 3
int64 EMISSION_TYPE_EURO5 = 4
int64 EMISSION_TYPE_EURO6 = 5
