#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 fuel_type
int64 FUEL_TYPE_RANGE_MIN = 0
int64 FUEL_TYPE_RANGE_MAX = 9
int64 FUEL_TYPE_UNKNOWN_FUEL = 0
int64 FUEL_TYPE_GASOLINE = 1
int64 FUEL_TYPE_ETHANOL = 2
int64 FUEL_TYPE_DIESEL = 3
int64 FUEL_TYPE_ELECTRIC = 4
int64 FUEL_TYPE_HYBRID = 5
int64 FUEL_TYPE_HYDROGEN = 6
int64 FUEL_TYPE_NAT_GAS_LIQUID = 7
int64 FUEL_TYPE_NAT_GAS_COMP = 8
int64 FUEL_TYPE_PROPANE = 9
