#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 gnssstatus
int64 GNSSSTATUS_UNAVAILABLE = 0
int64 GNSSSTATUS_IS_HEALTHY = 1
int64 GNSSSTATUS_IS_MONITORED = 2
int64 GNSSSTATUS_BASE_STATION_TYPE = 3
int64 GNSSSTATUS_A_PDOPOF_UNDER5 = 4
int64 GNSSSTATUS_IN_VIEW_OF_UNDER5 = 5
int64 GNSSSTATUS_LOCAL_CORRECTIONS_PRESENT = 6
int64 GNSSSTATUS_NETWORK_CORRECTIONS_PRESENT = 7
