#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 heading_confidence_dsrc
int64 HEADING_CONFIDENCE_DSRC_UNAVAILABLE = 0
int64 HEADING_CONFIDENCE_DSRC_PREC10DEG = 1
int64 HEADING_CONFIDENCE_DSRC_PREC05DEG = 2
int64 HEADING_CONFIDENCE_DSRC_PREC01DEG = 3
int64 HEADING_CONFIDENCE_DSRC_PREC0_1DEG = 4
int64 HEADING_CONFIDENCE_DSRC_PREC0_05DEG = 5
int64 HEADING_CONFIDENCE_DSRC_PREC0_01DEG = 6
int64 HEADING_CONFIDENCE_DSRC_PREC0_0125DEG = 7
