#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



StationID station_id

# Optional Field
bool lane_id_present 0
LaneID lane_id

# Optional Field
bool node_xy_present 0
NodeOffsetPointXY node_xy

# Optional Field
bool time_reference_present 0
TimeReference time_reference
