#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 lane_attributes_tracked_vehicle
int64 LANE_ATTRIBUTESTRACKED_VEHICLE_SPEC_REVOCABLE_LANE = 0
int64 LANE_ATTRIBUTESTRACKED_VEHICLE_SPEC_COMMUTER_RAIL_ROAD_TRACK = 1
int64 LANE_ATTRIBUTESTRACKED_VEHICLE_SPEC_LIGHT_RAIL_ROAD_TRACK = 2
int64 LANE_ATTRIBUTESTRACKED_VEHICLE_SPEC_HEAVY_RAIL_ROAD_TRACK = 3
int64 LANE_ATTRIBUTESTRACKED_VEHICLE_SPEC_OTHER_RAIL_TYPE = 4
