#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 lane_attributes_sidewalk
int64 LANE_ATTRIBUTESSIDEWALK_SIDEWALK_REVOCABLE_LANE = 0
int64 LANE_ATTRIBUTESSIDEWALK_BICYLE_USE_ALLOWED = 1
int64 LANE_ATTRIBUTESSIDEWALK_IS_SIDEWALK_FLY_OVER_LANE = 2
int64 LANE_ATTRIBUTESSIDEWALK_WALK_BIKES = 3
