#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool max_vehicle_height_present 0
VehicleHeight max_vehicle_height

# Optional Field
bool max_vehicle_weight_present 0
VehicleMass max_vehicle_weight
