#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 layer_type
int64 LAYER_TYPE_NONE = 0
int64 LAYER_TYPE_MIXED_CONTENT = 1
int64 LAYER_TYPE_GENERAL_MAP_DATA = 2
int64 LAYER_TYPE_INTERSECTION_DATA = 3
int64 LAYER_TYPE_CURVE_DATA = 4
int64 LAYER_TYPE_ROADWAY_SECTION_DATA = 5
int64 LAYER_TYPE_PARKING_AREA_DATA = 6
int64 LAYER_TYPE_SHARED_LANE_DATA = 7
