#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool time_stamp_present 0
MinuteOfTheYear time_stamp

MsgCount msg_issue_revision

# Optional Field
bool layer_type_present 0
LayerType layer_type

# Optional Field
bool layer_id_present 0
LayerID layer_id

# Optional Field
bool intersections_present 0
IntersectionGeometryList intersections

# Optional Field
bool road_segments_present 0
RoadSegmentList road_segments

# Optional Field
bool data_parameters_present 0
DataParameters data_parameters

# Optional Field
bool restriction_list_present 0
RestrictionClassList restriction_list

# Optional Field
bool regional_present 0
RegMapData[] regional #size(1..4)
