#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool ptv_request_present 0
PtvRequestType ptv_request

# Optional Field
bool node_link_present 0
NodeLink node_link

# Optional Field
bool node_present 0
Node node
