#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



int64 id

# Optional Field
bool lane_present 0
LaneID lane

# Optional Field
bool connection_id_present 0
LaneConnectionID connection_id

# Optional Field
bool intersection_id_present 0
IntersectionID intersection_id
