#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 node_list_xy_container_select 0
int64 NODE_LIST_XY_NOTHING = 0
int64 NODE_LIST_XY_NODES = 1
int64 NODE_LIST_XY_COMPUTED = 2

# container 1
NodeSetXY nodes

# container 2
ComputedLane computed

