#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 node_offset_point_xy_container_select 0
int64 NODE_OFFSET_POINT_XY_NOTHING = 0
int64 NODE_OFFSET_POINT_XY_NODE_XY1 = 1
int64 NODE_OFFSET_POINT_XY_NODE_XY2 = 2
int64 NODE_OFFSET_POINT_XY_NODE_XY3 = 3
int64 NODE_OFFSET_POINT_XY_NODE_XY4 = 4
int64 NODE_OFFSET_POINT_XY_NODE_XY5 = 5
int64 NODE_OFFSET_POINT_XY_NODE_XY6 = 6
int64 NODE_OFFSET_POINT_XY_NODE_LAT_LON = 7
int64 NODE_OFFSET_POINT_XY_REGIONAL = 8

# container 1
NodeXY20b nodexy1

# container 2
NodeXY22b nodexy2

# container 3
NodeXY24b nodexy3

# container 4
NodeXY26b nodexy4

# container 5
NodeXY28b nodexy5

# container 6
NodeXY32b nodexy6

# container 7
NodeLLmD64b nodelat_lon

# container 8
RegNodeOffsetPointXY regional

