#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



int64 id

# Optional Field
bool lane_present 0
LaneID lane

# Optional Field
bool connection_id_present 0
LaneConnectionID connection_id

# Optional Field
bool intersection_id_present 0
IntersectionID intersection_id
