#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool local_node_present 0
NodeAttributeXYList local_node

# Optional Field
bool disabled_present 0
SegmentAttributeXYList disabled

# Optional Field
bool enabled_present 0
SegmentAttributeXYList enabled

# Optional Field
bool data_present 0
LaneDataAttributeList data

# Optional Field
bool d_width_present 0
OffsetB10 d_width

# Optional Field
bool d_elevation_present 0
OffsetB10 d_elevation

# Optional Field
bool regional_present 0
RegNodeAttributeSetXY[] regional #size(1..4)
