#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 priority_request_type
int64 PRIORITY_REQUEST_TYPE_PRIORITY_REQUEST_TYPE_RESERVED = 0
int64 PRIORITY_REQUEST_TYPE_PRIORITY_REQUEST = 1
int64 PRIORITY_REQUEST_TYPE_PRIORITY_REQUEST_UPDATE = 2
int64 PRIORITY_REQUEST_TYPE_PRIORITY_CANCELLATION = 3
