#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 ptv_request_type
int64 PTV_REQUEST_TYPE_PRE_REQUEST = 0
int64 PTV_REQUEST_TYPE_MAIN_REQUEST = 1
int64 PTV_REQUEST_TYPE_DOOR_CLOSE_REQUEST = 2
int64 PTV_REQUEST_TYPE_CANCEL_REQUEST = 3
int64 PTV_REQUEST_TYPE_EMERGENCY_REQUEST = 4
