#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 region_id
int64 REGION_ID_RANGE_MIN = 0
int64 REGION_ID_RANGE_MAX = 255
int64 REGION_ID_NO_REGION = 0
int64 REGION_ID_ADD_GRP_A = 1
int64 REGION_ID_ADD_GRP_B = 2
int64 REGION_ID_ADD_GRP_C = 3
