#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 rejected_reason
int64 REJECTED_REASON_UNKNOWN = 0
int64 REJECTED_REASON_EXCEPTIONAL_CONDITION = 1
int64 REJECTED_REASON_MAX_WAITING_TIME_EXCEEDED = 2
int64 REJECTED_REASON_PT_PRIORITY_DISABLED = 3
int64 REJECTED_REASON_HIGHER_PTPRIORITY_GRANTED = 4
int64 REJECTED_REASON_VEHICLE_TRACKING_UNKNOWN = 5
