#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



BasicVehicleRole role

# Optional Field
bool subrole_present 0
RequestSubRole subrole

# Optional Field
bool request_present 0
RequestImportanceLevel request

# Optional Field
bool iso3883_present 0
Iso3833VehicleType iso3883

# Optional Field
bool hpms_type_present 0
VehicleType hpms_type

# Optional Field
bool regional_present 0
RegionalExtension regional
