#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



VehicleID id

RequestID request

MsgCount sequence_number

# Optional Field
bool role_present 0
BasicVehicleRole role

# Optional Field
bool type_data_present 0
RequestorType type_data
