#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



# Optional Field
bool time_stamp_present 0
MinuteOfTheYear time_stamp

# Optional Field
bool name_present 0
DescriptiveName name

IntersectionStateList intersections

# Optional Field
bool regional_present 0
RegSPAT[] regional #size(1..4)
