#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 speed_confidence_dsrc
int64 SPEED_CONFIDENCE_DSRC_UNAVAILABLE = 0
int64 SPEED_CONFIDENCE_DSRC_PREC100MS = 1
int64 SPEED_CONFIDENCE_DSRC_PREC10MS = 2
int64 SPEED_CONFIDENCE_DSRC_PREC5MS = 3
int64 SPEED_CONFIDENCE_DSRC_PREC1MS = 4
int64 SPEED_CONFIDENCE_DSRC_PREC0_1MS = 5
int64 SPEED_CONFIDENCE_DSRC_PREC0_05MS = 6
int64 SPEED_CONFIDENCE_DSRC_PREC0_01MS = 7
