#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool start_time_present 0
TimeMark start_time

TimeMark min_end_time

# Optional Field
bool max_end_time_present 0
TimeMark max_end_time

# Optional Field
bool likely_time_present 0
TimeMark likely_time

# Optional Field
bool confidence_present 0
TimeIntervalConfidence confidence

# Optional Field
bool next_time_present 0
TimeMark next_time
