#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 transit_vehicle_status
int64 TRANSIT_VEHICLE_STATUS_LOADING = 0
int64 TRANSIT_VEHICLE_STATUS_AN_ADAUSE = 1
int64 TRANSIT_VEHICLE_STATUS_A_BIKE_LOAD = 2
int64 TRANSIT_VEHICLE_STATUS_DOOR_OPEN = 3
int64 TRANSIT_VEHICLE_STATUS_CHARGING = 4
int64 TRANSIT_VEHICLE_STATUS_AT_STOP_LINE = 5
