#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 transmission_state
int64 TRANSMISSION_STATE_NEUTRAL = 0
int64 TRANSMISSION_STATE_PARK = 1
int64 TRANSMISSION_STATE_FORWARD_GEARS = 2
int64 TRANSMISSION_STATE_REVERSE_GEARS = 3
int64 TRANSMISSION_STATE_RESERVED1 = 4
int64 TRANSMISSION_STATE_RESERVED2 = 5
int64 TRANSMISSION_STATE_RESERVED3 = 6
int64 TRANSMISSION_STATE_UNAVAILABLE = 7
