#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 day_of_week
int64 DAY_OF_WEEK_UNUSED = 0
int64 DAY_OF_WEEK_MONDAY = 1
int64 DAY_OF_WEEK_TUESDAY = 2
int64 DAY_OF_WEEK_WEDNESDAY = 3
int64 DAY_OF_WEEK_THURSDAY = 4
int64 DAY_OF_WEEK_FRIDAY = 5
int64 DAY_OF_WEEK_SATURDAY = 6
int64 DAY_OF_WEEK_SUNDAY = 7
