#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



DestinationRoadType der_type

# Optional Field
bool road_number_identifier_present 0
int64 road_number_identifier
int64 ROAD_NUMBER_IDENTIFIER_RANGE_MIN = 1
int64 ROAD_NUMBER_IDENTIFIER_RANGE_MAX = 999

# Optional Field
bool road_number_text_present 0
string road_number_text
