#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool vehicle_height_present 0
Distance vehicle_height

# Optional Field
bool vehicle_width_present 0
Distance vehicle_width

# Optional Field
bool vehicle_length_present 0
Distance vehicle_length

# Optional Field
bool vehicle_weight_present 0
Weight vehicle_weight
