#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool junction_direction_present 0
int64 junction_direction
int64 JUNCTION_DIRECTION_RANGE_MIN = 1
int64 JUNCTION_DIRECTION_RANGE_MAX = 128

# Optional Field
bool roundabout_cw_direction_present 0
int64 roundabout_cw_direction
int64 ROUNDABOUT_CW_DIRECTION_RANGE_MIN = 1
int64 ROUNDABOUT_CW_DIRECTION_RANGE_MAX = 128

# Optional Field
bool roundabout_ccw_direction_present 0
int64 roundabout_ccw_direction
int64 ROUNDABOUT_CCW_DIRECTION_RANGE_MIN = 1
int64 ROUNDABOUT_CCW_DIRECTION_RANGE_MAX = 128

DDDIOLIST io_list
