#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool speed_limit_max_present 0
int64 speed_limit_max
int64 SPEED_LIMIT_MAX_RANGE_MIN = 0
int64 SPEED_LIMIT_MAX_RANGE_MAX = 250

# Optional Field
bool speed_limit_min_present 0
int64 speed_limit_min
int64 SPEED_LIMIT_MIN_RANGE_MIN = 0
int64 SPEED_LIMIT_MIN_RANGE_MAX = 250

CodeUnits unit
int64 UNIT_RANGE_MIN = 0
int64 UNIT_RANGE_MAX = 1
