#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 repeating_period_day_types
int64 REPEATING_PERIOD_DAY_TYPES_NATIONAL_HOLIDAY = 0
int64 REPEATING_PERIOD_DAY_TYPES_EVEN_DAYS = 1
int64 REPEATING_PERIOD_DAY_TYPES_ODD_DAYS = 2
int64 REPEATING_PERIOD_DAY_TYPES_MARKET_DAY = 3
