#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 eu_vehicle_category_l
int64 EU_VEHICLE_CATEGORY_L_L1 = 0
int64 EU_VEHICLE_CATEGORY_L_L2 = 1
int64 EU_VEHICLE_CATEGORY_L_L3 = 2
int64 EU_VEHICLE_CATEGORY_L_L4 = 3
int64 EU_VEHICLE_CATEGORY_L_L5 = 4
int64 EU_VEHICLE_CATEGORY_L_L6 = 5
int64 EU_VEHICLE_CATEGORY_L_L7 = 6
