#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:05 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 eu_vehicle_category_o
int64 EU_VEHICLE_CATEGORY_O_O1 = 0
int64 EU_VEHICLE_CATEGORY_O_O2 = 1
int64 EU_VEHICLE_CATEGORY_O_O3 = 2
int64 EU_VEHICLE_CATEGORY_O_O4 = 3
