#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 eu_vehicle_category_code_container_select 0
int64 EU_VEHICLE_CATEGORY_CODE_NOTHING = 0
int64 EU_VEHICLE_CATEGORY_CODE_EU_VEHICLE_CATEGORY_L = 1
int64 EU_VEHICLE_CATEGORY_CODE_EU_VEHICLE_CATEGORY_M = 2
int64 EU_VEHICLE_CATEGORY_CODE_EU_VEHICLE_CATEGORY_N = 3
int64 EU_VEHICLE_CATEGORY_CODE_EU_VEHICLE_CATEGORY_O = 4

# container 1
EuVehicleCategoryL eu_vehicle_category_l

# container 2
EuVehicleCategoryM eu_vehicle_category_m

# container 3
EuVehicleCategoryN eu_vehicle_category_n

# container 4
EuVehicleCategoryO eu_vehicle_category_o

