#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Range range

WGS84AngleValue stationary_horizontal_opening_angle_start

WGS84AngleValue stationary_horizontal_opening_angle_end

# Optional Field
bool vertical_opening_angle_start_present 0
CartesianAngleValue vertical_opening_angle_start

# Optional Field
bool vertical_opening_angle_end_present 0
CartesianAngleValue vertical_opening_angle_end

# Optional Field
bool sensor_position_offset_present 0
OffsetPoint sensor_position_offset

# Optional Field
bool sensor_height_present 0
SensorHeight sensor_height
