#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool node_center_point_present 0
OffsetPoint node_center_point

SemiRangeLength semi_major_range_length

SemiRangeLength semi_minor_range_length

WGS84AngleValue semi_major_range_orientation

# Optional Field
bool semi_height_present 0
SemiRangeLength semi_height
