#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 cartesian_angle_value
int64 CARTESIAN_ANGLE_VALUE_RANGE_MIN = 0
int64 CARTESIAN_ANGLE_VALUE_RANGE_MAX = 3601
int64 CARTESIAN_ANGLE_VALUE_ZERO_POINT_ONE_DEGREE = 1
int64 CARTESIAN_ANGLE_VALUE_ONE_DEGREE = 10
int64 CARTESIAN_ANGLE_VALUE_UNAVAILABLE = 3601
