#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 class_confidence
int64 CLASS_CONFIDENCE_RANGE_MIN = 0
int64 CLASS_CONFIDENCE_RANGE_MAX = 101
int64 CLASS_CONFIDENCE_UNKNOWN = 0
int64 CLASS_CONFIDENCE_ONE_PERCENT = 1
int64 CLASS_CONFIDENCE_ONE_HUNDRED_PERCENT = 100
int64 CLASS_CONFIDENCE_UNAVAILABLE = 101
