#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



StationType station_type

# Optional Field
bool perceived_object_container_segment_info_present 0
PerceivedObjectContainerSegmentInfo perceived_object_container_segment_info

ReferencePosition reference_position
