#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



StationType station_type

# Optional Field
bool perceived_object_container_segment_info_present 0
PerceivedObjectContainerSegmentInfo perceived_object_container_segment_info

ReferencePosition reference_position
