#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



CpmManagementContainer management_container

# Optional Field
bool station_data_container_present 0
StationDataContainer station_data_container

# Optional Field
bool sensor_information_container_present 0
SensorInformationContainer sensor_information_container

# Optional Field
bool perceived_object_container_present 0
PerceivedObjectContainer perceived_object_container

# Optional Field
bool free_space_addendum_container_present 0
FreeSpaceAddendumContainer free_space_addendum_container

NumberOfPerceivedObjects number_of_perceived_objects
