#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 distance_value
int64 DISTANCE_VALUE_RANGE_MIN = -132768
int64 DISTANCE_VALUE_RANGE_MAX = 132767
int64 DISTANCE_VALUE_ZERO_POINT_ZERO_ONE_METER = 1
int64 DISTANCE_VALUE_ONE_METER = 100
