#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 dynamic_status
int64 DYNAMIC_STATUS_RANGE_MIN = 0
int64 DYNAMIC_STATUS_RANGE_MAX = 2
int64 DYNAMIC_STATUS_DYNAMIC = 0
int64 DYNAMIC_STATUS_HAS_BEEN_DYNAMIC = 1
int64 DYNAMIC_STATUS_STATIC = 2
