#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



FreeSpaceConfidence free_space_confidence

FreeSpaceArea free_space_area

# Optional Field
bool sensor_idlist_present 0
SensorIdList sensor_idlist

# Optional Field
bool shadowing_applies_present 0
ShadowingApplies shadowing_applies
