#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 front_overhang
int64 FRONT_OVERHANG_RANGE_MIN = 0
int64 FRONT_OVERHANG_RANGE_MAX = 50
int64 FRONT_OVERHANG_ZERO_POINT_ONE_METER = 1
int64 FRONT_OVERHANG_ONE_METER = 10
