#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 hitch_point_offset
int64 HITCH_POINT_OFFSET_RANGE_MIN = 0
int64 HITCH_POINT_OFFSET_RANGE_MAX = 100
int64 HITCH_POINT_OFFSET_ZERO_POINT_ONE_METER = 1
int64 HITCH_POINT_OFFSET_ONE_METER = 10
