#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 longitudinal_lane_position_value
int64 LONGITUDINAL_LANE_POSITION_VALUE_RANGE_MIN = 0
int64 LONGITUDINAL_LANE_POSITION_VALUE_RANGE_MAX = 32767
int64 LONGITUDINAL_LANE_POSITION_VALUE_ZERO_POINT_ONE_METER = 1
