#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool lane_id_present 0
LaneID lane_id

# Optional Field
bool longitudinal_lane_position_present 0
LongitudinalLanePosition longitudinal_lane_position
