#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


# CHOICE! - Choose exactly of the containers
int64 node_offset_point_z_container_select 0
int64 NODE_OFFSET_POINT_Z_NOTHING = 0
int64 NODE_OFFSET_POINT_Z_NODE_Z1 = 1
int64 NODE_OFFSET_POINT_Z_NODE_Z2 = 2
int64 NODE_OFFSET_POINT_Z_NODE_Z3 = 3
int64 NODE_OFFSET_POINT_Z_NODE_Z4 = 4
int64 NODE_OFFSET_POINT_Z_NODE_Z5 = 5
int64 NODE_OFFSET_POINT_Z_NODE_Z6 = 6

# container 1
OffsetB10 nodez1

# container 2
OffsetB11 nodez2

# container 3
OffsetB12 nodez3

# container 4
OffsetB13 nodez4

# container 5
OffsetB14 nodez5

# container 6
OffsetB16 nodez6

