#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 object_dimension_value
int64 OBJECT_DIMENSION_VALUE_RANGE_MIN = 0
int64 OBJECT_DIMENSION_VALUE_RANGE_MAX = 1023
int64 OBJECT_DIMENSION_VALUE_ZERO_POINT_ONE_METER = 1
int64 OBJECT_DIMENSION_VALUE_ONE_METER = 10
