#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 object_dimension_confidence
int64 OBJECT_DIMENSION_CONFIDENCE_RANGE_MIN = 0
int64 OBJECT_DIMENSION_CONFIDENCE_RANGE_MAX = 102
int64 OBJECT_DIMENSION_CONFIDENCE_ZERO_POINT_ZERO_ONE_METER = 1
int64 OBJECT_DIMENSION_CONFIDENCE_ONE_METER = 100
int64 OBJECT_DIMENSION_CONFIDENCE_OUT_OF_RANGE = 101
int64 OBJECT_DIMENSION_CONFIDENCE_UNAVAILABLE = 102
