#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 object_ref_point
int64 OBJECT_REF_POINT_RANGE_MIN = 0
int64 OBJECT_REF_POINT_RANGE_MAX = 8
int64 OBJECT_REF_POINT_MID = 0
int64 OBJECT_REF_POINT_BOTTOM_LEFT = 1
int64 OBJECT_REF_POINT_MID_LEFT = 2
int64 OBJECT_REF_POINT_TOP_LEFT = 3
int64 OBJECT_REF_POINT_BOTTOM_MID = 4
int64 OBJECT_REF_POINT_TOP_MID = 5
int64 OBJECT_REF_POINT_BOTTOM_RIGHT = 6
int64 OBJECT_REF_POINT_MID_RIGHT = 7
int64 OBJECT_REF_POINT_TOP_RIGHT = 8
