#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 object_confidence
int64 OBJECT_CONFIDENCE_RANGE_MIN = 0
int64 OBJECT_CONFIDENCE_RANGE_MAX = 101
int64 OBJECT_CONFIDENCE_UNKNOWN = 0
int64 OBJECT_CONFIDENCE_ONE_PERCENT = 1
int64 OBJECT_CONFIDENCE_ONE_HUNDRED_PERCENT = 100
int64 OBJECT_CONFIDENCE_UNAVAILABLE = 101
