#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Heading heading

Speed speed

# Optional Field
bool vehicle_orientation_angle_present 0
WGS84Angle vehicle_orientation_angle

# Optional Field
bool drive_direction_present 0
DriveDirection drive_direction

# Optional Field
bool longitudinal_acceleration_present 0
LongitudinalAcceleration longitudinal_acceleration

# Optional Field
bool lateral_acceleration_present 0
LateralAcceleration lateral_acceleration

# Optional Field
bool vertical_acceleration_present 0
VerticalAcceleration vertical_acceleration

# Optional Field
bool yaw_rate_present 0
YawRate yaw_rate

# Optional Field
bool pitch_angle_present 0
CartesianAngle pitch_angle

# Optional Field
bool roll_angle_present 0
CartesianAngle roll_angle

# Optional Field
bool vehicle_length_present 0
VehicleLength vehicle_length

# Optional Field
bool vehicle_width_present 0
VehicleWidth vehicle_width

# Optional Field
bool vehicle_height_present 0
VehicleHeight vehicle_height

# Optional Field
bool trailer_data_container_present 0
TrailerDataContainer trailer_data_container
