#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 other_sublass_type
int64 OTHER_SUBLASS_TYPE_RANGE_MIN = 0
int64 OTHER_SUBLASS_TYPE_RANGE_MAX = 255
int64 OTHER_SUBLASS_TYPE_UNKNOWN = 0
int64 OTHER_SUBLASS_TYPE_ROAD_SIDE_UNIT = 1
