#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Identifier object_id

# Optional Field
bool sensor_idlist_present 0
SensorIdList sensor_idlist

TimeOfMeasurement time_of_measurement

# Optional Field
bool object_age_present 0
ObjectAge object_age

# Optional Field
bool object_confidence_present 0
ObjectConfidence object_confidence

ObjectDistanceWithConfidence x_distance

ObjectDistanceWithConfidence y_distance

# Optional Field
bool z_distance_present 0
ObjectDistanceWithConfidence z_distance

SpeedExtended x_speed

SpeedExtended y_speed

# Optional Field
bool z_speed_present 0
SpeedExtended z_speed

# Optional Field
bool x_acceleration_present 0
LongitudinalAcceleration x_acceleration

# Optional Field
bool y_acceleration_present 0
LateralAcceleration y_acceleration

# Optional Field
bool z_acceleration_present 0
VerticalAcceleration z_acceleration

# Optional Field
bool yaw_angle_present 0
CartesianAngle yaw_angle

# Optional Field
bool planar_object_dimension1_present 0
ObjectDimension planar_object_dimension1

# Optional Field
bool planar_object_dimension2_present 0
ObjectDimension planar_object_dimension2

# Optional Field
bool vertical_object_dimension_present 0
ObjectDimension vertical_object_dimension

# Optional Field
bool object_ref_point_present 0
ObjectRefPoint object_ref_point

# Optional Field
bool dynamic_status_present 0
DynamicStatus dynamic_status

# Optional Field
bool classification_present 0
ObjectClassDescription classification

# Optional Field
bool matched_position_present 0
MatchedPosition matched_position
