#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 person_subclass_type
int64 PERSON_SUBCLASS_TYPE_RANGE_MIN = 0
int64 PERSON_SUBCLASS_TYPE_RANGE_MAX = 255
int64 PERSON_SUBCLASS_TYPE_UNKNOWN = 0
int64 PERSON_SUBCLASS_TYPE_PEDESTRIAN = 1
int64 PERSON_SUBCLASS_TYPE_PERSON_IN_WHEELCHAIR = 2
int64 PERSON_SUBCLASS_TYPE_CYCLIST = 3
int64 PERSON_SUBCLASS_TYPE_PERSON_WITH_STROLLER = 4
int64 PERSON_SUBCLASS_TYPE_PERSON_ON_SKATES = 5
int64 PERSON_SUBCLASS_TYPE_PERSON_GROUP = 6
