#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



Identifier sensor_id

SensorType type

DetectionArea detection_area

# Optional Field
bool free_space_confidence_present 0
FreeSpaceConfidence free_space_confidence
