#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 sensor_type
int64 SENSOR_TYPE_RANGE_MIN = 0
int64 SENSOR_TYPE_RANGE_MAX = 15
int64 SENSOR_TYPE_UNDEFINED = 0
int64 SENSOR_TYPE_RADAR = 1
int64 SENSOR_TYPE_LIDAR = 2
int64 SENSOR_TYPE_MONOVIDEO = 3
int64 SENSOR_TYPE_STEREOVISION = 4
int64 SENSOR_TYPE_NIGHTVISION = 5
int64 SENSOR_TYPE_ULTRASONIC = 6
int64 SENSOR_TYPE_PMD = 7
int64 SENSOR_TYPE_FUSION = 8
int64 SENSOR_TYPE_INDUCTIONLOOP = 9
int64 SENSOR_TYPE_SPHERICAL_CAMERA = 10
int64 SENSOR_TYPE_ITSSAGGREGATION = 11
