#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 


int64 speed_value_extended
int64 SPEED_VALUE_EXTENDED_RANGE_MIN = -16383
int64 SPEED_VALUE_EXTENDED_RANGE_MAX = 16383
int64 SPEED_VALUE_EXTENDED_STANDSTILL = 0
int64 SPEED_VALUE_EXTENDED_ONE_CENTIMETER_PER_SEC = 1
int64 SPEED_VALUE_EXTENDED_UNAVAILABLE = 16383
