#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



RefPointId ref_point_id

HitchPointOffset hitch_point_offset

FrontOverhang front_overhang

RearOverhang rear_overhang

# Optional Field
bool trailer_width_present 0
VehicleWidth trailer_width

# Optional Field
bool hitch_angle_present 0
CartesianAngle hitch_angle
