#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



RefPointId ref_point_id

HitchPointOffset hitch_point_offset

FrontOverhang front_overhang

RearOverhang rear_overhang

# Optional Field
bool trailer_width_present 0
VehicleWidth trailer_width

# Optional Field
bool hitch_angle_present 0
CartesianAngle hitch_angle
