#
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)
# Copyright: Patrizia Neubauer (https://github.com/patrizianeubauer)
# 



Range range

CartesianAngleValue horizontal_opening_angle_start

CartesianAngleValue horizontal_opening_angle_end

# Optional Field
bool vertical_opening_angle_start_present 0
CartesianAngleValue vertical_opening_angle_start

# Optional Field
bool vertical_opening_angle_end_present 0
CartesianAngleValue vertical_opening_angle_end
