#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)



# Optional Field
bool ref_point_id_present 0
RefPointId ref_point_id

XSensorOffset x_sensor_offset

YSensorOffset y_sensor_offset

# Optional Field
bool z_sensor_offset_present 0
ZSensorOffset z_sensor_offset

VehicleSensorPropertyList vehicle_sensor_property_list
