#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 wgs84angle_value
int64 WGS84ANGLE_VALUE_RANGE_MIN = 0
int64 WGS84ANGLE_VALUE_RANGE_MAX = 3601
int64 WGS84ANGLE_VALUE_WGS84NORTH = 0
int64 WGS84ANGLE_VALUE_WGS84EAST = 900
int64 WGS84ANGLE_VALUE_WGS84SOUTH = 1800
int64 WGS84ANGLE_VALUE_WGS84WEST = 2700
int64 WGS84ANGLE_VALUE_UNAVAILABLE = 3601
