#
# Created by script of Patrizia Neubauer (https://github.com/patrizianeubauer)
# Date: Fri Jan 20 13:59:04 2023
# Generated with ROS-Parser from vehicleCAPTAIN Toolbox (https://github.com/virtual-vehicle/vehicle_captain_asn1_parser)


int64 ysensor_offset
int64 YSENSOR_OFFSET_RANGE_MIN = -1000
int64 YSENSOR_OFFSET_RANGE_MAX = 1000
int64 YSENSOR_OFFSET_ZERO_POINT_ZERO_ONE_METER = 1
int64 YSENSOR_OFFSET_ONE_METER = 100
